### ISSUE TITLE
getVideoId not work for this type of urls

### ISSUE THREAD

**Issue by gurkirtanbabri** [AnasOnGit/is-youtube-url#1]
const urls = [
  "https://www.youtube.com/embed/9ObEUNeTBBM",
  "https://www.youtube.com/watch/9ObEUNeTBBM",
  "https://www.youtube.com/live/9ObEUNeTBBM",
]

**Comment by AnasOnGit** [comment]
Hi! I just wanted to let you know that I have added support for these URLs. Thanks for bringing this up!
